/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    SatelliteTreeColumnHeader: typeof import('./src/components/SatelliteTreeColumnHeader.vue')['default']
    SatelliteTreeRowHeader: typeof import('./src/components/SatelliteTreeRowHeader.vue')['default']
    TreeCheckbox: typeof import('./src/components/TreeCheckbox.vue')['default']
  }
}
